### ISSUE TITLE
bilibili 下载失败

### ISSUE THREAD

**Issue by mengyyy** [iawia002/Lulu#18]
```
lulu: version 0.1.8, a tiny downloader that scrapes the web.
lulu: Namespace(URL=['https://www.bilibili.com/bangumi/play/ep173329'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy='127.0.0.1:1080', stream=None, timeout=600, url=False, version=False)
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/lulu/extractors/bilibili.py", line 179, in entry
    cid = re.search(r'cid=(\d+)', self.page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lulu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/lulu/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lulu/common.py", line 1486, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lulu/common.py", line 1376, in script_main
    **extra
  File "/usr/local/lib/python3.5/dist-packages/lulu/common.py", line 1120, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lulu/common.py", line 1477, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lulu/extractor.py", line 60, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lulu/extractors/bilibili.py", line 154, in prepare
    self.entry(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lulu/extractors/bilibili.py", line 183, in entry
    cid = re.search(r'"cid":(\d+)', self.page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
对比发现是 self.page 有问题 相比直接拉取的少了cid
```
lulu: page | <!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>原书·原书使：第3话_番剧_bilibili_哔哩哔哩</title>
    <meta name="description" content="“只为了你而编织的故事。”让故事得以实现的，少女们的愿望。散布于世界的故事“原书”。少女们与“原书”相遇，被其选中，获得魔法，终成“原书使”。这是，以这样的“原书使”为目标的“见习原书使”少女们，与“">
    <meta name="keywords" content="原书·原书使">
    <meta name="author" content="哔哩哔哩番剧">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta property="og:title" content="原书·原书使">
    <meta property="og:type" content="video.anime">
    <meta property="og:url" content="//www.bilibili.com/bangumi/play/ss21721/">
    <meta property="og:image" content="http://i0.hdslb.com/bfs/archive/3cc5bcc674ca1619a919830be88089d67705f9f1.jpg">
    <link rel="shortcut icon" href="//static.hdslb.com/images/favicon.ico">
    <script type="application/ld+json">{
        "@context": "https://zhanzhang.baidu.com/contexts/cambrian.jsonld",
        "@id": "/bangumi/play/ep173329?from=baidu_official",
        "title": "原书·原书使：第3话_番剧_bilibili_哔哩哔哩",
        "images": ["http://i0.hdslb.com/bfs/archive/3cc5bcc674ca1619a919830be88089d67705f9f1.jpg"],
        "description": "“只为了你而编织的故事。”让故事得以实现的，少女们的愿望。散布于世界的故事“原书”。少女们与“原书”相遇，被其选中，获得魔法，终成“原书使”。这是，以这样的“原书使”为目标的“见习原书使”少女们，与“",
        "pubDate": "2018-01-10T16:00:00"
    }
    </script>
</head>
<body>
<h1>原书·原书使：第3话_番剧_bilibili_哔哩哔哩</h1>
<ul>

    <li>
        <a href="//www.bilibili.com/bangumi/play/ep173327">
            <h4>物语症候群</h4>
            <img src="http://i2.hdslb.com/bfs/archive/9a244b104e65a6d6e95aaec870fcaf19103bf10c.jpg" alt="">
        </a>
    </li>

    <li>
        <a href="//www.bilibili.com/bangumi/play/ep173328">
            <h4>第一次的魔法</h4>
            <img src="http://i0.hdslb.com/bfs/archive/5474fbb2b2be41d28b79c0c056f457f8e4502fa0.jpg" alt="">
        </a>
    </li>

    <li>
        <a href="//www.bilibili.com/bangumi/play/ep173329">
            <h4>魔女之夜到来</h4>
            <img src="http://i0.hdslb.com/bfs/archive/3cc5bcc674ca1619a919830be88089d67705f9f1.jpg" alt="">
        </a>
    </li>

</ul>
</body>
</html>
```
直接拉取
```
<!DOCTYPE html>
<html>
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <link href="//s1.hdslb.com" rel="dns-prefetch"/>
  <link href="//s2.hdslb.com" rel="dns-prefetch"/>
  <link href="//s3.hdslb.com" rel="dns-prefetch"/>
  <link href="//i0.hdslb.com" rel="dns-prefetch"/>
  <link href="//i1.hdslb.com" rel="dns-prefetch"/>
  <link href="//i2.hdslb.com" rel="dns-prefetch"/>
  <link href="//static.hdslb.com" rel="dns-prefetch"/>
  <title>
   原书·原书使：第3话_番剧_bilibili_哔哩哔哩
  </title>
  <meta content="“只为了你而编织的故事。”让故事得以实现的，少女们的愿望。散布于世界的故事“原书”。少女们与“原书”相 遇，被其选中，获得魔法，终成“原书使”。这是，以这样的“原书使”为目标的“见习原书使”少女们，与“" name="description"/>
  <meta content="原书·原书使" name="keywords"/>
  <meta content="哔哩哔哩番剧" name="author"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="原书·原书使" property="og:title"/>
  <meta content="video.anime" property="og:type"/>
  <meta content="//www.bilibili.com/bangumi/play/ss21721/" property="og:url"/>
  <meta content="http://i0.hdslb.com/bfs/archive/3cc5bcc674ca1619a919830be88089d67705f9f1.jpg" property="og:image"/>
  <meta content="666.10" name="spm_prefix"/>
  <link href="//static.hdslb.com/images/favicon.ico" rel="shortcut icon"/>
  <link href="//static.hdslb.com/phoenix/dist/css/comment.min.css" rel="stylesheet" type="text/css"/>
  <script>
   (function () {
            var ua = window.navigator.userAgent,
                agents = ['Android', 'iPhone', 'SymbianOS', 'Windows Phone', 'iPod'],
                isPC = true;
            for (var i = 0, len = agents.length; i < len; i++) {
                if (ua.indexOf(agents[i]) > 0) {
                    isPC = false;
                    break;
                }
            }
            if (isPC == false) {
                var href = window.location.href.replace('www', 'm');
                window.location.href = href;
            }
        })();
  </script>
  <script src="//static.hdslb.com/js/jquery.min.js" type="text/javascript">
  </script>
  <script src="//static.hdslb.com/js/swfobject.js" type="text/javascript">
  </script>
  <script src="//static.hdslb.com/js/video.min.js" type="text/javascript">
  </script>
  <script src="//static.hdslb.com/vip/dist/js/vipPlugin.js" type="text/javascript">
  </script>
  <script src="//s1.hdslb.com/bfs/static/bangumi/play/js/promise.js">
  </script>
  <script src="//s1.hdslb.com/bfs/seed/jinkela/header/header.js" type="text/javascript">
  </script>
  <script src="//s2.hdslb.com/bfs/cm/st/bundle.js" type="text/javascript">
  </script>
  <link as="script" href="//s1.hdslb.com/bfs/static/bangumi/play/js/manifest.7770e0e3.js" rel="preload"/>
  <link as="script" href="//s1.hdslb.com/bfs/static/bangumi/play/js/vendor.7770e0e3.js" rel="preload"/>
  <link as="script" href="//s1.hdslb.com/bfs/static/bangumi/play/js/bangumi-play.7770e0e3.js" rel="preload"/>
  <link as="style" href="//s1.hdslb.com/bfs/static/bangumi/play/css/bangumi-play.7770e0e3.css" rel="preload"/>
  <link href="//s1.hdslb.com/bfs/static/bangumi/play/css/bangumi-play.7770e0e3.css" rel="stylesheet"/>
 </head>
 <body>
  <div class="z-top-container has-menu" style="height:234px">
  </div>
  <div class="main-container" data-server-rendered="true" id="app">
   <div class="bangumi-header clearfix">
    <div class="header-info">
     <h1 title="原书·原书使：第3话 魔女之夜到来">
      原书·原书使：第3话 魔女之夜到来
     </h1>
     <div class="info-second">
      <a href="//bangumi.bilibili.com/22/" target="_blank">
       <span class="info-sec-type">
        番剧
       </span>
      </a>
      <span class="info-sec-area">
       日本
      </span>
      <span class="info-sec-pub">
       连载中, 每周四22:30更新
      </span>
      <a class="info-sec-av" href="//www.bilibili.com/video/av18728500/" target="_blank">
       AV18728500
      </a>
     </div>
     <div class="count-wrapper clearfix">
      <div class="view-count">
       <i>
       </i>
       <span>
        97.4万
       </span>
      </div>
      <div class="danmu-count">
       <i>
       </i>
       <span>
        2.4万
       </span>
      </div>
      <div class="bangumi-coin-wrap" title="投硬币枚数4505">
       <i class="bangumi-coin" style="display:;">
       </i>
       <i class="bangumi-coin-d" style="display:none;">
       </i>
       <span class="coin-status">
        硬币
       </span>
       <span id="v_ctimes">
        4505
       </span>
      </div>
      <div class="bangumi-order-wrap" title="追番数27.4万">
       <i class="bangumi-order" style="display:;">
       </i>
       <i class="bangumi-order-d" style="display:none;">
       </i>
       <span class="bangumi-order-status">
        追番
       </span>
       <span id="v_ctimes">
        27.4万
       </span>
      </div>
     </div>
     <div class="header-ad-wrapper">
     </div>
    </div>
    <!-- -->
    <div class="ad-f clearfix">
     <div class="left ad-fl data-id-ad" data-loc-id="124" style="display: none;">
     </div>
     <div class="right ad-fr data-id-ad" data-loc-id="126" style="display: none;">
     </div>
    </div>
   </div>
   <div class="player-wrapper" style="background-image:none;">
    <!-- -->
    <div class="bangumi-player">
     <div class="player-content" id="bofqi" style="display:none;">
     </div>
     <!-- -->
     <!-- -->
     <div class="mini-player-move">
      <span title="点击按住拖动">
      </span>
      <i>
      </i>
     </div>
     <div id="heimu">
     </div>
    </div>
   </div>
   <div class="bangumi-info-wrapper">
    <div class="bangumi-info clearfix">
     <div class="info-cover">
      <a href="//www.bilibili.com/bangumi/media/md11752/" target="_blank">
       <img alt="" src="//i0.hdslb.com/bfs/bangumi/74ebc38e3ec260441d0460ecc80b6548d3746890.jpg@240w_320h.jpg"/>
      </a>
      <!-- -->
     </div>
     <div class="info-right">
      <div class="info-title clearfix">
       <a href="//www.bilibili.com/bangumi/media/md11752/" target="_blank">
        <h2>
         原书·原书使
        </h2>
       </a>
       <!-- -->
       <div class="func-module clearfix">
        <div class="bangumi-btn">
         <div class="btn-follow">
          <i>
          </i>
          追番
         </div>
        </div>
        <div class="share-module">
         <ul class="share-list clearfix">
          <li class="share-btn btn-app" share-type="app">
          </li>
          <li class="share-btn btn-weibo" share-type="weibo">
          </li>
          <li class="share-btn btn-qqzone" share-type="qqzone">
          </li>
          <li class="share-btn btn-qq" share-type="qq">
          </li>
          <li class="share-btn btn-baidu" share-type="baidu">
          </li>
         </ul>
        </div>
       </div>
      </div>
      <!-- -->
      <!-- -->
      <div class="bangumi-list-wrapper">
       <div class="top-block">
        <div class="ss-list-wrapper">
         <div class="slider-wrapper">
          <div class="slider-content">
           <ul class="season-list">
            <li class="season-item on">
             TV
            </li>
           </ul>
          </div>
          <div class="slider-contro clearfix">
           <div class="contro-item" style="display:none;">
           </div>
           <!-- -->
           <i class="slider-prev-mask" style="display:none;">
           </i>
           <!-- -->
           <i class="slider-next-mask" style="display:none;">
           </i>
          </div>
         </div>
        </div>
        <ul class="mode-select clearfix">
         <li class="detail-mode selected" title="详细模式">
         </li>
         <li class="simple-mode" title="精简模式">
         </li>
        </ul>
       </div>
       <div class="bottom-block">
        <div class="slider-wrapper">
         <div class="slider-content">
          <ul class="episode-list">
           <li class="episode-item" title="第1话：物语症候群">
            <h4 class="ep-index">
             第1话
            </h4>
            <p class="ep-title" style="display:;">
             物语症候群
            </p>
            <!-- -->
           </li>
           <li class="episode-item" title="第2话：第一次的魔法">
            <h4 class="ep-index">
             第2话
            </h4>
            <p class="ep-title" style="display:;">
             第一次的魔法
            </p>
            <!-- -->
           </li>
           <li class="episode-item on" title="第3话：魔女之夜到来">
            <h4 class="ep-index">
             第3话
            </h4>
            <p class="ep-title" style="display:;">
             魔女之夜到来
            </p>
            <!-- -->
           </li>
           <!-- -->
          </ul>
         </div>
         <div class="slider-contro clearfix">
          <div class="contro-item" style="display:none;">
          </div>
          <!-- -->
          <i class="slider-prev-mask" style="display:none;">
          </i>
          <!-- -->
          <i class="slider-next-mask" style="display:none;">
          </i>
         </div>
        </div>
       </div>
      </div>
     </div>
     <!-- -->
    </div>
   </div>
   <div class="bangumi-media">
    <div class="bangumi-media-header">
     <h4>
      点评
     </h4>
     <!-- -->
     <a class="btn-more-review" href="/bangumi/media/md11752/" target="_blank">
      查看全部点评
     </a>
    </div>
    <div class="bangumi-media-body clearfix">
     <!-- -->
     <ul class="bangumi-review-list clearfix">
     </ul>
    </div>
   </div>
   <div class="sponsor-wrapper clearfix">
    <div class="sponsor-left-area">
     <div class="sponsor-rank">
      <div class="sponsor-rank-header">
       <h3>
        承包榜
       </h3>
       <ul class="sponsor-rank-tab clearfix">
        <li class="active">
         七日榜
        </li>
        <li>
         总榜
        </li>
        <div class="indicator" style="left:0px;width:0px;">
        </div>
       </ul>
       <div class="show-sponsor-rank">
        查看承包榜
       </div>
      </div>
      <div class="sponsor-rank-body">
       <ul class="sponsor-rank-list" style="display:none;">
        <li class="empty">
         前排虚位以待，快来承包吧
        </li>
       </ul>
       <div class="load-state rank-loading">
        <span class="loading">
         正在加载...
        </span>
        <!-- -->
        <!-- -->
       </div>
      </div>
     </div>
    </div>
    <div class="sponsor-right-area">
     <div class="img-wrapper">
      <!-- -->
     </div>
     <p class="sponsor-count-info">
      成为第一个承包人吧！
     </p>
     <div class="sponsor-btn">
      我要承包
     </div>
    </div>
   </div>
   <!-- -->
   <div class="other-wrapper clearfix">
    <div class="comment-wrapper common">
     <div class="comment-title b-head">
      <span class="results">
      </span>
      评论
     </div>
     <div class="comm">
     </div>
    </div>
    <div class="recom-wrapper">
     <div class="bangumi-recom">
      <h4 class="recom-title">
       相关视频推荐
      </h4>
      <ul class="recom-list clearfix">
      </ul>
     </div>
    </div>
   </div>
   <!-- -->
   <!-- -->
   <!-- -->
   <!-- -->
   <!-- -->
   <!-- -->
   <!-- -->
   <!-- -->
   <div class="bangumi-nav-right" style="opacity:0;">
    <div class="nav-goto-top">
    </div>
    <div class="nav-mini-switch" style="display:;">
     mini
     <br/>
     ON
    </div>
   </div>
   <!-- -->
   <div class="short-review-masker" style="display:none;">
    <div class="short-review-content">
     <div class="dialog-close">
     </div>
     <div class="review-header-wrap">
      <div class="review-edit-header">
       <a class="media-img" href="//www.bilibili.com/bangumi/media/md11752/" target="_blank">
        <img alt="" src="//i0.hdslb.com/bfs/bangumi/74ebc38e3ec260441d0460ecc80b6548d3746890.jpg@100w_133h.jpg"/>
       </a>
       <div class="media-info">
        <h4>
         原书·原书使
        </h4>
        <p class="rate-tip">
         请发表你对这部作品的评分
        </p>
        <div class="rate-wrap">
         <ul class="rate-star clearfix">
          <li>
           <i class="icon-star">
           </i>
          </li>
          <li>
           <i class="icon-star">
           </i>
          </li>
          <li>
           <i class="icon-star">
           </i>
          </li>
          <li>
           <i class="icon-star">
           </i>
          </li>
          <li>
           <i class="icon-star">
           </i>
          </li>
         </ul>
         <!-- -->
        </div>
       </div>
      </div>
     </div>
     <div class="review-body-wrap">
      <textarea name="short-review" placeholder="" value=""></textarea>
      <span class="tip" style="color:#99a2aa;">
       0/100
      </span>
      <button class="mr-btn">
       发表短评
      </button>
     </div>
     <a class="mr-long-review" href="//www.bilibili.com/bangumi/media/md11752/edit" target="_blank">
      想写长评，点这里 &gt;
     </a>
    </div>
   </div>
  </div>
  <script>
   window.__INITIAL_STATE__={"ver":{"mobile":false,"ios":false,"android":false,"windowsPhone":false,"iPhone":false,"ios9":false,"iPad":false,"webApp":false,"microMessenger":false,"weibo":false,"uc":false,"qq":false,"baidu":false,"mqq":false,"mBaidu":false,"iqiyi":false,"qqLive":false,"safari":true,"youku":false,"ie":false,"edge":false,"bili":false,"biliVer":0},"loginInfo":{"isLogin":null},"canReview":false,"userShortReview":{},"userLongReview":{},"userScore":0,"userCoined":false,"isPlayerTrigger":false,"special":false,"area":0,"app":false,"epId":173329,"ssId":21721,"mdId":11752,"mediaInfo":{"actors":"键村叶月：楠木友利\n土御门静：末柄里惠\n尤米莉娅·卡赞：Lynn\n琳·迪布斯：日高里菜\n玛利亚·拉斯普京：大津爱理\n阿加特·阿利亚：加隈亚衣\n亚瑟·潘多拉贡：上田丽奈\n加澄有子：本渡枫\n学园长：冈村明美\n李雪梅：吉冈麻耶\n摩诃迦利：镰仓有那","areas":[{"id":2,"name":"日本"}],"cover":"http:\u002F\u002Fi0.hdslb.com\u002Fbfs\u002Fbangumi\u002F74ebc38e3ec260441d0460ecc80b6548d3746890.jpg","evaluate":"“只为了你而编织的故事。”让故事得以实现的，少女们的愿望。散布于世界的故事“ 原书”。少女们与“原书”相遇，被其选中，获得魔法，终成“原书使”。这是，以这样的“原书使”为目标的“见习原书使”少女们，与“原书”一同编织出自己的故事的梦与魔法与青春的物语——","is_paster_ads":0,"jp_title":"メルヘン・メドヘン","link":"http:\u002F\u002Fwww.bilibili.com\u002Fbangumi\u002Fmedia\u002Fmd11752\u002F","media_id":11752,"mode":2,"season_id":21721,"season_status":2,"season_title":"TV","season_type":1,"square_cover":"http:\u002F\u002Fi0.hdslb.com\u002Fbfs\u002Fbangumi\u002F1fbe57ee123f734837d29accbf85bddca2a83973.jpg","staff":"原案&系列构成：松智洋\n原案协力：StoryWorks\n角色原案：监督\n总监督：斋藤久\n监督：上田繁\n角色设计：森川侑纪\n剧本：松智洋、朝浦、门田祐一、金月龙之介\n色彩设计：齐藤麻记\n美术监 督：下元智子\n摄影监督：村上优作\n编辑：广濑清志\n音乐：rionos\n音乐制作：Lantis\n音响监督：森下广人\n音响制作：叶音\n动画制作：Hoods Entertainment\n制作：原书·原书使制作委员会","style":["轻改","魔法","日常"],"title":"原书·原书使","total_ep":12},"mediaRating":{"count":615,"score":9},"epInfo":{"aid":18728500,"cid":30547424,"cover":"http:\u002F\u002Fi0.hdslb.com\u002Fbfs\u002Farchive\u002F3cc5bcc674ca1619a919830be88089d67705f9f1.jpg","ep_id":173329,"episode_status":2,"from":"bangumi","index":"3","index_title":"魔女之夜到来","mid":928123,"page":1,"vid":""},"epList":[{"aid":18202358,"cid":29717241,"cover":"http:\u002F\u002Fi2.hdslb.com\u002Fbfs\u002Farchive\u002F9a244b104e65a6d6e95aaec870fcaf19103bf10c.jpg","ep_id":173327,"episode_status":2,"from":"bangumi","index":"1","index_title":"物语症候群","mid":928123,"page":1,"vid":""},{"aid":18452487,"cid":30113040,"cover":"http:\u002F\u002Fi0.hdslb.com\u002Fbfs\u002Farchive\u002F5474fbb2b2be41d28b79c0c056f457f8e4502fa0.jpg","ep_id":173328,"episode_status":2,"from":"bangumi","index":"2","index_title":"第一次的魔法","mid":928123,"page":1,"vid":""},{"aid":18728500,"cid":30547424,"cover":"http:\u002F\u002Fi0.hdslb.com\u002Fbfs\u002Farchive\u002F3cc5bcc674ca1619a919830be88089d67705f9f1.jpg","ep_id":173329,"episode_status":2,"from":"bangumi","index":"3","index_title":"魔女之夜到来","mid":928123,"page":1,"vid":""}],"newestEp":{"desc":"连载中, 每周四22:30更新","id":173329,"index":"3","is_new":1},"seasonList":[{"is_new":1,"season_id":21721,"season_title":"TV","title":"原书·原书使"}],"seasonStat":{"coins":4505,"danmakus":24424,"favorites":273804,"views":974042},"userStat":{"loaded":false,"error":false,"follow":0,"pay":0,"payPackPaid":0,"sponsor":0,"watchProgress":{"lastEpId":-1,"lastEpIndex":"","lastTime":0}},"upInfo":{"avatar":"http:\u002F\u002Fi1.hdslb.com\u002Fbfs\u002Fface\u002F60a9153609998b04301dc5b8ed44c41b537a2268.jpg","mid":928123,"pendant":{"image":"","name":"","pid":0},"uname":"哔哩哔哩番剧"},"rightsInfo":{"allow_bp":1,"allow_download":0,"allow_review":1,"copyright":"dujia","is_preview":0,"watch_platform":0},"pubInfo":{"is_finish":0,"is_started":1,"pub_time":"2018-01-11","pub_time_show":"2018年01月11日","weekday":4},"recomList":[],"playerRecomList":[],"paster":{},"payPack":{},"payMent":{},"activity":{},"spending":0,"sponsorTotal":{"code":0,"result":{"ep_bp":0,"users":0,"mine":{},"list":[]}},"sponsorWeek":{"code":0,"result":{"ep_bp":0,"users":0,"mine":{},"list":[]}},"sponsorTotalCount":0,"miniOn":true,"seasonFollowed":false};(function(){var s;(s=document.currentScript||document.scripts[document.scripts.length-1]).parentNode.removeChild(s);}());
  </script>
  <script defer="" src="//s1.hdslb.com/bfs/static/bangumi/play/js/manifest.7770e0e3.js">
  </script>
  <script defer="" src="//s1.hdslb.com/bfs/static/bangumi/play/js/vendor.7770e0e3.js">
  </script>
  <script defer="" src="//s1.hdslb.com/bfs/static/bangumi/play/js/bangumi-play.7770e0e3.js">
  </script>
  <script type="text/javascript">
   if (!+"\v1") {
        document.body.innerHTML = "<div style='background: #00a1d6; text-align: center; padding: 10px 0; color: #fff;'> 为了保护你的账号安全，bilibili已不支持IE8及以下版本浏览器访问，建议你升级到IE最新版本浏览器，或使用Chrome等其他浏览器。</div>"
    }
  </script>
  <div class="footer bili-footer report-wrap-module" id="home_footer">
  </div>
  <script charset="utf-8" src="//static.hdslb.com/common/js/footer.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   window.bid = 13;
        window.spmReportData = {}
        window.reportConfig = {
            sample : 1,
            scrollTracker: true,
            msgObjects : 'spmReportData'
        }
  </script>
 </body>
</html>
```
cid  位于 **_window.__INITIAL_STATE___** 内

**Comment by mengyyy** [comment]
擦恢复了……误报了……
