### ISSUE TITLE
合并时出错

### ISSUE THREAD

**Issue by Refarin** [iawia002/Lulu#41]
不明白哪出问题了

```
lulu

 http://v.youku.com/v_show/id_XMzMxODQ3MDc3Ng==.html?spm=a2hzp.8244740.0.0 --debug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzMxODQ3MDc3Ng==&ccode=0507&client_ip=192.168.1.1&utid=PW/8EsrqYScCAduLv5mvbZdn&client_ts=1517650232
site:                优酷 (Youku)
title:               纪录片:夜幕下的故事
stream:
    - format:        mp4hd3
      container:     mp4
      video-profile: 1080P
      size:          399.2 MiB (418591604 bytes)
      m3u8_url:      http://pl.cp12.wasu.tv/playlist/m3u8?vid=XMzMxODQ3MDc3Ng%3D%3D&type=hd3&ups_client_netip=db8bbf99&ups_ts=1517650240&utid=PW%2F8EsrqYScCAduLv5mvbZdn&ccode=0507&psid=ea4715cb8d22b4cfdeac155061686b54&duration=1295&expire=18000&ups_key=e5d687903cb03b213720a90a344d643c
    # download-with: lulu --format=mp4hd3 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMzMxODQ3MDc3Ng==

Downloading 纪录片-夜幕下的故事.mp4 ...
 100% (399.2/399.2MB) ├██████████████████████████████████████┤[10/10]  116 MB/slulu: version 0.2.5, a tiny downloader that scrapes the web.
lulu: Namespace(URL=['http://v.youku.com/v_show/id_XMzMxODQ3MDc3Ng==.html?spm=a2hzp.8244740.0.0'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\lulu.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\common.py", line 1483, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\common.py", line 1373, in script_main
    **extra
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\common.py", line 1119, in download_main
    download(url, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\common.py", line 1474, in any_download
    m.download(url, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\extractors\youku.py", line 349, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\extractor.py", line 85, in download_by_url
    self.download(**kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\extractor.py", line 290, in download
    av=stream_id in self.dash_streams
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\common.py", line 852, in download_urls
    concat_mp4(parts, output_filepath)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\processor\join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\processor\join_mp4.py", line 876, in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\processor\join_mp4.py", line 717, in read_mp4
    atoms = parse_atoms(stream)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\processor\join_mp4.py", line 708, in parse_atoms
    atom = read_atom(stream)
  File "c:\program files (x86)\python36-32\lib\site-packages\lulu\processor\join_mp4.py", line 700, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x05\x00\x00\x00': 1179407865
```

**Comment by iawia002** [comment]
@Refarin 我用的是 mac，下载合并都没有出问题。你这个问题我再研究一下

**Comment by iawia002** [comment]
@Refarin 你安装 ffmpeg 后再试一下

**Comment by Refarin** [comment]
@iawia002  可以了，感谢大佬
