### ISSUE TITLE
部分B站视频无法下载

### ISSUE THREAD

**Issue by note286** [iawia002/Lulu#42]
这三个B站视频无法下载，不知道什么原因，我是macOS，pip安装的lulu
```console
lulu https://www.bilibili.com/video/av19077840
lulu: [error] oops, something went wrong.
lulu: don't panic, c'est la vie. please try the following steps:
lulu:   (1) Rule out any network problem.
lulu:   (2) Make sure lulu is up-to-date.
lulu:   (3) Check if the issue is already known, on
lulu:         https://github.com/iawia002/Lulu/issues
lulu:   (4) Run the command with '--debug' option,
lulu:       and report this issue with the full output.
```
```console
lulu https://www.bilibili.com/video/av19050849
lulu https://www.bilibili.com/video/av19009512
```
```console
lulu https://www.bilibili.com/video/av19009512 --debug
[DEBUG] url_locations: https://www.bilibili.com/video/av19009512
[DEBUG] get_content: https://www.bilibili.com/video/av19009512/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=31012091&player=1&quality=4&ts=1517654278&sign=5e1df9da5cfabaa82123b0d652761a84
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=31012091&player=1&quality=3&ts=1517654278&sign=9565a77088a66ed6bdb45c34d5ec2047
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=31012091&player=1&quality=2&ts=1517654278&sign=04d3d372bd73f51ef97c3a66637429a3
lulu: version 0.2.5, a tiny downloader that scrapes the web.
lulu: Namespace(URL=['https://www.bilibili.com/video/av19009512'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/lulu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/lulu/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/common.py", line 1483, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/common.py", line 1373, in script_main
    **extra
  File "/usr/local/lib/python3.6/site-packages/lulu/common.py", line 1119, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/common.py", line 1474, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/extractor.py", line 62, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/extractors/bilibili.py", line 166, in prepare
    self.entry(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/extractors/bilibili.py", line 208, in entry
    cid, re.search('bangumi', self.url) is not None, **kwargs
  File "/usr/local/lib/python3.6/site-packages/lulu/extractors/bilibili.py", line 122, in download_by_vid
    self.parse_bili_xml(api_xml)
  File "/usr/local/lib/python3.6/site-packages/lulu/extractors/bilibili.py", line 108, in parse_bili_xml
    stream_type, container = self.bilibili_stream_type(urls_list)
  File "/usr/local/lib/python3.6/site-packages/lulu/extractors/bilibili.py", line 59, in bilibili_stream_type
    url = urls[0]
IndexError: list index out of range
```

**Comment by iawia002** [comment]
@note286 更新一下 0.3.0 就好了

**Comment by iawia002** [comment]
fixed in f5e31658f1516c4b16349420b21d874d95b025d1
