### ISSUE TITLE
优酷的春晚无法下载

### ISSUE THREAD

**Issue by note286** [iawia002/Lulu#58]
`lulu http://v.youku.com/v_show/id_XMzQwNDgwNzM1Ng==.html`
```
Traceback (most recent call last):
  File "/usr/local/bin/lulu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/lulu/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/common.py", line 1409, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/lulu/common.py", line 1264, in script_main
    set_proxy(parse_host(args.http_proxy))
  File "/usr/local/lib/python3.6/site-packages/lulu/common.py", line 990, in parse_host
    if re.match(r'^(\d+)$', host) is not None:
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

`lulu: version 0.4.0, a tiny downloader that scrapes the web.`

**Comment by iawia002** [comment]
更新一下 0.4.1 就好了

**Comment by note286** [comment]
@iawia002 实在是不好意思，我提问前也更新了，但是我的pip源是中科大的，估计有延迟，不是最新的，导致更新后还是0.4.0，刚才换成pip官方的源就好了，非常感谢作者辛勤劳动！

**Comment by iawia002** [comment]
@note286 没事，其实是我的问题，我一个地方改错了，才在 0.4.0 后又马上发了一个 0.4.1
