### ISSUE TITLE
dilidili broken

### ISSUE THREAD

**Issue by atusoft** [iawia002/Lulu#79]
`lulu --debug 'http://www.dilidili.wang/watch/11601/'`

[DEBUG] get_content: http://www.dilidili.wang/watch/11601/
lulu: version 0.4.7, a tiny downloader that scrapes the web.
lulu: Namespace(URL=['http://www.dilidili.wang/watch/11601/'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, thread=0, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1373, in url_to_module
    assert video_host and video_url
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lulu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lulu/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1417, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1307, in script_main
    **extra
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1045, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1408, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lulu/extractors/dilidili.py", line 23, in dilidili_download
    any_download(url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1407, in any_download
    m, url = url_to_module(url)
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1375, in url_to_module
    url = google_search(url)
  File "/usr/local/lib/python3.6/dist-packages/lulu/common.py", line 1350, in google_search
    url = 'https://www.google.com/search?tbm=vid&q=%s' % parse.quote(keywords)
  File "/usr/lib/python3.6/urllib/parse.py", line 787, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.6/urllib/parse.py", line 812, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by iawia002** [comment]
dilidili 不推荐使用，它的视频的根源基本都是优酷、爱奇艺上面的，而它自己用了一个第三方的解析服务，解析优酷、爱奇艺上的视频来放。你这个视频的根源是优酷上的：<http://v.youku.com/v_show/id_XMzI5MDU3OTg0.html>，B 站上也能[找到](https://www.bilibili.com/bangumi/play/ss844/)，推荐你用 B 站或者优酷的地址来下载

**Comment by Justsoos** [comment]
dilidili 这网站 ssl 证书都过期2月了，都没人管。。。。真是草台班子啊
