### ISSUE TITLE
下载bilibili视频报错Index out of range?

### ISSUE THREAD

**Issue by XDcedar** [iawia002/Lulu#81]
lulu --debug  -i --playlist https://www.bilibili.com/video/av1967587/
随便找了别的视频试了试 没有这个问题 只有这一个是这样..
```
[DEBUG] url_locations: https://www.bilibili.com/video/av19675870
[DEBUG] get_content: http://www.bilibili.com/widget/getPageList?aid=19675870
[DEBUG] url_locations: http://www.bilibili.com/video/av19675870/index_1.html
[DEBUG] get_content: https://www.bilibili.com/video/av19675870/index_1.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=32082733&player=1&quality=4&ts=1520254218&sign=dfe1d7648a8965a5c849d1c19a3fe837
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=32082733&player=1&quality=3&ts=1520254218&sign=ac012e24d66c3d234a6f753461cb78b1
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=32082733&player=1&quality=2&ts=1520254218&sign=4888117767df74dff17e9cff57a713f4
lulu: version 0.2.3, a tiny downloader that scrapes the web.
lulu: Namespace(URL=['https://www.bilibili.com/video/av19675870'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=True, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\lulu.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\lulu\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python36\lib\site-packages\lulu\common.py", line 1486, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\program files\python36\lib\site-packages\lulu\common.py", line 1376, in script_main
    **extra
  File "c:\program files\python36\lib\site-packages\lulu\common.py", line 1118, in download_main
    download_playlist(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\lulu\common.py", line 1482, in any_download_playlist
    m.download_playlist(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\lulu\extractors\bilibili.py", line 429, in bilibili_download_playlist_by_url
    site.download_by_url(page_url, subtitle=subtitle, **kwargs)
  File "c:\program files\python36\lib\site-packages\lulu\extractor.py", line 62, in download_by_url
    self.prepare(**kwargs)
  File "c:\program files\python36\lib\site-packages\lulu\extractors\bilibili.py", line 166, in prepare
    self.entry(**kwargs)
  File "c:\program files\python36\lib\site-packages\lulu\extractors\bilibili.py", line 208, in entry
    cid, re.search('bangumi', self.url) is not None, **kwargs
  File "c:\program files\python36\lib\site-packages\lulu\extractors\bilibili.py", line 122, in download_by_vid
    self.parse_bili_xml(api_xml)
  File "c:\program files\python36\lib\site-packages\lulu\extractors\bilibili.py", line 108, in parse_bili_xml
    stream_type, container = self.bilibili_stream_type(urls_list)
  File "c:\program files\python36\lib\site-packages\lulu\extractors\bilibili.py", line 59, in bilibili_stream_type
    url = urls[0]
IndexError: list index out of range
```

**Comment by iawia002** [comment]
更新一下朋友，早就修复了的，你这个版本才 0.2.3

**Comment by XDcedar** [comment]
哈哈尴尬..早上更新过 没注意到网络问题导致更新失败了..还以为用的是最新版..

**Comment by iawia002** [comment]
下 B 站的视频的话可以试一下 https://github.com/iawia002/annie
go 语言写的，运行速度比 lulu 快很多

**Comment by XDcedar** [comment]
啊! 非常感谢! 我去试试!
